repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
    - id: black
      language_version: python3.11

-   repo: https://github.com/pycqa/isort
    rev: 9.0.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8

-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v6.0.0
   hooks:
    - id: detect-private-key

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['audit', '.secrets.baseline']




ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] Fixing issues with pre-commit'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit automatically updated revs.'
